name: CI/CD Pipeline for Wisecow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: mahijoe/server:latest

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest

    - name: Start Minikube
      run: minikube start --driver=docker

    - name: Minikube status
      run: minikube status

    - name: Check kubectl context
      run: kubectl config current-context

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl rollout status deployment/server-deployment
        kubectl get pods
        kubectl get services

    - name: Test service URLs
      run: |
        minikube service list
        minikube service server-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service server-service --url)

