name: CI/CD Pipeline for Wisecow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: mahijoe/server:latest

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest

    - name: Start Minikube
      run: minikube start --driver=docker

    - name: Minikube status
      run: minikube status

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl rollout status deployment/server-deployment
        kubectl get pods
        kubectl get services
        kubectl describe service server-service
        kubectl get endpoints server-service
        kubectl logs $(kubectl get pods -l app=server -o jsonpath='{.items[0].metadata.name}')

    - name: Expose Service and Test
      run: |
        # Expose the service using NodePort
        kubectl expose deployment server-deployment --type=NodePort --name=server-service --port=80 --target-port=80
        
        # Wait for service to be available
        sleep 10
        
        # Retrieve the Minikube IP and service URL
        MINIKUBE_IP=$(minikube ip)
        NODE_PORT=$(kubectl get svc server-service -o=jsonpath='{.spec.ports[0].nodePort}')
        
        # Print the URL for debugging
        echo "Service URL: http://${MINIKUBE_IP}:${NODE_PORT}"
        
        # Test the service
        curl -v http://${MINIKUBE_IP}:${NODE_PORT}

