name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build and deploy to Minikube
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: mahijoe/server:latest

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest

    - name: Start Minikube
      run: minikube start --driver=docker

    - name: Minikube status
      run: minikube status

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Expose and access the service
      run: |
        # Wait for the NodePort service to be ready
        sleep 30

        # Get the Minikube IP
        MINIKUBE_IP=$(minikube ip)

        # Get the NodePort service port
        NODE_PORT=$(kubectl get svc server-service -o=jsonpath='{.spec.ports[0].nodePort}')

        # Print the URL for debugging
        SERVICE_URL="http://${MINIKUBE_IP}:${NODE_PORT}"
        echo "Service URL: ${SERVICE_URL}"

        # Access the service
        curl -v ${SERVICE_URL}
       
