name: CI/CD Pipeline for Wisecow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: mahijoe/server:latest

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.4.0
      with:
        minikube version: 'v1.24.0'  # specify a version to avoid the 404 error
        kubernetes version: 'v1.21.0'  # specify the Kubernetes version
        driver: docker

    - name: Minikube status
      run: minikube status

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

